# -*- coding: utf-8 -*-
"""Bio_ClinicalBERT finetuned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w5gxSm6LfF4R_quJOuYmfmpJAQNyn5DZ
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, BertForSequenceClassification, TrainingArguments, Trainer
import torch
import random
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

"""data filtering , encoding ,and visualization"""

data = pd.read_csv('/content/final_reports_with_labels.csv')

# count each cancer type
cancer_counts = data['cancer_type'].value_counts()
print(cancer_counts)

# Identify cancer types with counts of 200 or more
cancer_types_to_keep = cancer_counts[cancer_counts >= 200].index


filtered_data = data[data['cancer_type'].isin(cancer_types_to_keep)]


filtered_data.to_csv('filtered_cancer_types.csv', index=False)


print("Filtered data saved to 'filtered_cancer_types.csv'")

print(f"Filtered dataset contains {len(filtered_data)} rows.")

data = pd.read_csv('filtered_cancer_types.csv')

label_encoder = LabelEncoder()

data['cancer_type_encoded'] = label_encoder.fit_transform(data['cancer_type'])

print(data[['cancer_type', 'cancer_type_encoded']].head())

data.to_csv('encoded_cancer_types.csv', index=False)

print("Data with encoded labels saved to 'encoded_cancer_types.csv'")

# Get the mapping of cancer types to labels
label_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))


print("Cancer type to label mapping:")
for cancer_type, label in label_mapping.items():
    print(f"{cancer_type}: {label}")

pd.DataFrame(list(label_mapping.items()), columns=['cancer_type', 'label']).to_csv('label_mapping.csv', index=False)

import matplotlib.pyplot as plt

#plotting the distribution of cancer types after filtering

data = pd.read_csv('filtered_cancer_types.csv')

cancer_counts = data['cancer_type'].value_counts()

plt.figure(figsize=(12, 6))
ax = cancer_counts.plot(kind='bar', color='skyblue', edgecolor='black')

for index, value in enumerate(cancer_counts):
    plt.text(index, value + 5, str(value), ha='center', va='bottom', fontsize=10)


plt.title('Distribution of Cancer Types in Filtered Dataset', fontsize=14)
plt.xlabel('Cancer Type', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)


plt.show()


print("Cancer Type Distribution:\n")
print(cancer_counts)

!pip install transformers torch scikit-learn

import time

start = time.time()

if torch.cuda.is_available():
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# Set Random Seed
seed = 42
np.random.seed(seed)
torch.manual_seed(seed)
random.seed(seed)

data = pd.read_csv('encoded_cancer_types.csv')
data = data.sample(frac=1, random_state=42)  # Shuffle the data

print(data.head())
print(data.columns)

"""handling imbalanced data"""

from sklearn.utils.class_weight import compute_class_weight
import torch

# Calculate class weights
class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(data['cancer_type_encoded']),
    y=data['cancer_type_encoded']
)


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)


print("Class Weights:")
for i, weight in enumerate(class_weights):
    print(f"Class {i}: {weight:.4f}")

#The weights ensure that classes with fewer samples get higher importance during training.

num_classes = len(data['cancer_type_encoded'].unique())
print(num_classes)

#Loads the Bio_ClinicalBERT tokenizer
tokenizer = AutoTokenizer.from_pretrained("emilyalsentzer/Bio_ClinicalBERT")

#Loads the Bio_ClinicalBERT model
model = BertForSequenceClassification.from_pretrained("emilyalsentzer/Bio_ClinicalBERT", num_labels=num_classes)

X = list(data["text"]) #X will contain the pathology report texts, which are the input features for the model.
y = list(data["cancer_type_encoded"]) #y will contain the numeric labels corresponding to the cancer types.

print(f"Number of samples: {len(X)}")
print(f"Number of labels: {len(y)}")

print(f"Sample text: {X[0]}")
print(f"Corresponding label: {y[0]}")

from collections import Counter
print("Class distribution:", Counter(y))

# Split data into train, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=seed, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=seed, stratify=y_temp)

print(f"Training set size: {len(X_train)}")
print(f"Validation set size: {len(X_val)}")
print(f"Test set size: {len(X_test)}")

from collections import Counter
print("Training set class distribution:", Counter(y_train))
print("Validation set class distribution:", Counter(y_val))
print("Test set class distribution:", Counter(y_test))

#training set : 70%
#validation set : 15%
#test set : 15%

X_train_tokenized = tokenizer(X_train, padding=True, truncation=True, max_length=512, return_tensors="pt")
X_val_tokenized = tokenizer(X_val, padding=True, truncation=True, max_length=512, return_tensors="pt")
X_test_tokenized = tokenizer(X_test, padding=True, truncation=True, max_length=512, return_tensors="pt")



#ClinicalBERT uses a BERT architecture, which supports a maximum sequence length of 512 tokens.

print(f"Train tokenized shape: {X_train_tokenized['input_ids'].shape}")
print(f"Validation tokenized shape: {X_val_tokenized['input_ids'].shape}")
print(f"Test tokenized shape: {X_test_tokenized['input_ids'].shape}")

print(tokenizer.decode(X_train_tokenized["input_ids"][0]))

print(max([len(seq) for seq in X_train_tokenized['input_ids']]))#Ensure no sequences exceed 512 tokens

print("Max sequence length in training data:", max([len(seq) for seq in X_train_tokenized['input_ids']]))

class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        if self.labels:
            item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.encodings["input_ids"])

train_dataset = Dataset(X_train_tokenized, y_train)
val_dataset = Dataset(X_val_tokenized, y_val)
test_dataset = Dataset(X_test_tokenized, y_test)

print(len(train_dataset))  # Should match len(X_train_tokenized['input_ids']) and len(y_train)
print(len(val_dataset))    # Should match len(X_val_tokenized['input_ids']) and len(y_val)
print(len(test_dataset))   # Should match len(X_test_tokenized['input_ids']) and len(y_test)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# a function to compute evaluation metrics for classification tasks
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=1)
    accuracy = accuracy_score(labels, predictions)
    f1 = f1_score(labels, predictions, average='weighted')
    precision = precision_score(labels, predictions, average='weighted')
    recall = recall_score(labels, predictions, average='weighted')
    return {'accuracy': accuracy, 'f1': f1, 'precision': precision, 'recall': recall}

training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    greater_is_better=True,
    fp16=True,
    dataloader_num_workers=2,
    learning_rate=2e-5
)



from transformers import Trainer, EarlyStoppingCallback
from torch.nn import CrossEntropyLoss

class CustomTrainer(Trainer): #Subclass of Trainer that overrides the compute_loss method to use class weights during training.
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        # Extract the labels from inputs
        labels = inputs["labels"]
        # Forward pass
        outputs = model(**inputs)
        logits = outputs.logits
        # Compute weighted loss
        loss = CrossEntropyLoss(weight=class_weights_tensor)(logits, labels)
        return (loss, outputs) if return_outputs else loss


trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

print("Class Weights Tensor:", class_weights_tensor)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

print(f"Using device: {device}")
print(next(model.parameters()).device)

"""fine-tuning and saving the model"""

trainer.train()

trainer.save_model("clinicalbert_finetuned")

import pandas as pd


performance_metrics = {
    "Phase": ["Train", "Validation", "Test"],
    "Accuracy": [],
    "F1 Score": [],
    "Precision": [],
    "Recall": []
}

#
train_results = trainer.evaluate(train_dataset)
performance_metrics["Accuracy"].append(train_results['eval_accuracy'])
performance_metrics["F1 Score"].append(train_results['eval_f1'])
performance_metrics["Precision"].append(train_results['eval_precision'])
performance_metrics["Recall"].append(train_results['eval_recall'])

validation_results = trainer.evaluate(val_dataset)
performance_metrics["Accuracy"].append(validation_results['eval_accuracy'])
performance_metrics["F1 Score"].append(validation_results['eval_f1'])
performance_metrics["Precision"].append(validation_results['eval_precision'])
performance_metrics["Recall"].append(validation_results['eval_recall'])

test_results = trainer.evaluate(test_dataset)
performance_metrics["Accuracy"].append(test_results['eval_accuracy'])
performance_metrics["F1 Score"].append(test_results['eval_f1'])
performance_metrics["Precision"].append(test_results['eval_precision'])
performance_metrics["Recall"].append(test_results['eval_recall'])


df_performance = pd.DataFrame(performance_metrics)


df_performance.to_csv('model_performance.csv', index=False)


print(df_performance)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay


predictions = np.argmax(trainer.predict(test_dataset).predictions, axis=1)


cm = confusion_matrix(y_test, predictions)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=label_encoder.classes_)
disp.plot(cmap="viridis", xticks_rotation=45)
plt.title("Confusion Matrix")
plt.show()

from sklearn.metrics import classification_report


predictions = np.argmax(trainer.predict(test_dataset).predictions, axis=1)

print(classification_report(y_test, predictions, target_names=label_encoder.classes_))

# Save the tokenizer
tokenizer.save_pretrained("clinicalbert_finetuned")

# Save the fine-tuned model
model.save_pretrained("clinicalbert_finetuned")

# Zip the directory to download it
import shutil
shutil.make_archive("clinicalbert_finetuned", 'zip', "clinicalbert_finetuned")

# Download the zipped model directory
from google.colab import files
files.download("clinicalbert_finetuned.zip")

import shutil
from google.colab import files

# Zip the results directory
shutil.make_archive("results", 'zip', "results")

# Download the zip file
files.download("results.zip")

"""took 20 samples of the test set for further usage"""

import pandas as pd
from google.colab import files


original_data = pd.read_csv("filtered_cancer_types.csv")

# Extract patient filenames corresponding to the test set indices
patient_filename = original_data.iloc[X_test.index]['patient_filename'].values


test_data = pd.DataFrame({
    "patient_filename": patient_filename,
    "text": X_test,
    "cancer_type_encoded": y_test
})

# Randomly sample 20 rows from the test set
sampled_test_data = test_data.sample(n=20, random_state=42)

sampled_test_data.to_csv("sampled_test_data_from_test_set.csv", index=False)

files.download("sampled_test_data_from_test_set.csv")