# -*- coding: utf-8 -*-
"""LIME XAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5QmxZsloj9GKJWJmV3u35f_qakZmbha
"""

import zipfile


# Ensure the correct file name matches the uploaded file
with zipfile.ZipFile("clinicalbert_finetuned (1).zip", "r") as zip_ref:
    zip_ref.extractall("clinicalbert_finetuned")

import pandas as pd
sampled_test_data = pd.read_csv("sampled_test_data_from_test_set.csv")

# Preview the test data
print(sampled_test_data.head())

"""--------------------------------------------------------------------------"""

!pip install lime
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from lime.lime_text import LimeTextExplainer
import torch
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Load the tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("clinicalbert_finetuned")
model = AutoModelForSequenceClassification.from_pretrained("clinicalbert_finetuned")
model.eval()

# Set the device for inference
device = "cpu"  # Change to "cuda" if using GPU
model.to(device)


class_names = [
    "BLCA", "BRCA", "CESC", "COAD", "GBM", "HNSC", "KIRC", "KIRP",
    "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "SARC", "STAD", "THCA", "UCEC"
]
explainer = LimeTextExplainer(class_names=class_names)

# Prediction function for LIME
def predict_proba(texts):
    inputs = tokenizer(
        texts, padding=True, truncation=True, max_length=512, return_tensors="pt"
    )
    inputs = {key: val.to(device) for key, val in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)
        probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
    return probs.numpy()

# Set the text length to 512 characters for truncation


truncate_length = 512

# Iterate through each sample in the test data (make sure to replace sampled_test_data with actual data)
for i, row in sampled_test_data.iterrows():
    text = row["text"][:truncate_length]  # Truncate text to 512 characters
    true_label = row["cancer_type_encoded"]  # True label for the current sample

    print(f"\n=== Explaining Sample {i+1} ===")
    print(f"Text: {text[:150]}...")  # Print the first 150 characters of the text for overview

    inputs = tokenizer([text], padding=True, truncation=True, max_length=512, return_tensors="pt")
    inputs = {key: val.to(device) for key, val in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)
        prediction = torch.argmax(outputs.logits, dim=-1).item()

    predicted_class = class_names[prediction]
    print(f"Predicted class: {predicted_class}")



    try:

        exp = explainer.explain_instance(
            text,
            predict_proba,
            num_features=10,
            labels=[prediction],
            num_samples=200
        )


        exp.show_in_notebook(text=True)

    except Exception as e:
        # Handle exceptions (e.g., issues with explaining the sample)
        print(f"Error processing sample {i+1}: {e}")



print(sampled_test_data["cancer_type_encoded"].unique())

for i, row in sampled_test_data.iterrows():
    true_label = row["cancer_type_encoded"]
    print(f"True label (encoded): {true_label}, Class name: {class_names[true_label]}")