# -*- coding: utf-8 -*-
"""ORC + POST-PROCCESSING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RyCAckf8-MPW2F6K3Dwb8l-zenpVMWWv

# **Run pathology report images through AWS Textract (on server)**
"""

import random
import timeit
import glob, os
import pickle
import boto3

#Make directory for AWS Response files
new_directory = 'data/aws_response/'
if not os.path.exists(new_directory):
    os.makedirs(new_directory)

#Load Pathology Report Images - Separate image for each report page
imgs = glob.glob('imgs_for_aws/*.jpg')

#Initialize client
client = boto3.client('textract')

#Run AWS Textract
start = timeit.default_timer()

i=0 #Track Number of Reports Processed

for img in imgs:

    i+=1

    #Convert Image to bytearray
    with open(img, "rb") as image: #File will close automatically
        f = image.read()
        b = bytearray(f)

    #Run Analyze_Document, with table-annotation
    response_with_table = client.analyze_document(
    Document={'Bytes': b}, #base64-encoded bytes
    FeatureTypes=['TABLES'])

    #Save AWS Response
    pickle.dump(response_with_table, open(new_directory + img.split('/')[-1].replace('.jpg','_response')+".p", "wb" ))

    if i%100 == 0:
        print('Number of pages processed: ', i, ' Runtime (min):', round((timeit.default_timer()-start)/60,2))

stop = timeit.default_timer()

print('Total runtime: ', round((stop - start)/60/60,2), 'hours.')

"""# **Post-Process AWS Response Files: Identify and Remove TCGA QC Tables, Remove handwriting as annotated by AWS Output**



"""

import glob
import pickle
import pandas as pd
import os, shutil
from collections import Counter
import matplotlib.pyplot as plt
import random
import numpy as np
import regex
from PIL import Image, ImageDraw
from IPython.display import display

response_list = glob.glob('data/aws_response/*.p')
random.shuffle(response_list)

new_dir = 'post_table_and_handwriting_removal/'
if not os.path.exists(new_dir):
    os.makedirs(new_dir)

large_area_dir = new_dir+'/tables_drawn_area_geq_point05/'
if not os.path.exists(large_area_dir):
    os.makedirs(large_area_dir)


def detect_qc_table(img):

    match_list = []

    image_file = 'imgs_for_aws/' + img
    response =  pickle.load( open('aws_response/'+img.replace('.jpg','')+'_response.p', "rb" ))
    blocks = response['Blocks']
    image=Image.open(image_file)
    draw = ImageDraw.Draw(image)
    width, height = image.size

    keyword_dict = {'agnosis Discrep':{'left1':0,'top1':-.01,'left2':.3,'top2':.075},
                   'imary Tumor Site Discrep':{'left1':0,'top1':-.02,'left2':.3,'top2':.065},
                   'IPAA':{'left1':0,'top1':-.03,'left2':.3,'top2':.055},
                   'rior Malignancy History':{'left1':0,'top1':-.04,'left2':.3,'top2':.045},
                   'ual/Syn':{'left1':0,'top1':-.05,'left2':.3,'top2':.035},
                   'ase is \(cir':{'left1':0,'top1':-.06,'left2':.3,'top2':.025},
                   'eviewer Initials':{'left1':0,'top1':-.07,'left2':.3,'top2':.015},
                   'ate Reviewed':{'left1':-.085,'top1':-.065,'left2':.22,'top2':.015},
                   'ISQUALI':{'left1':-.16,'top1':-.06,'left2':.13,'top2':.015}}

    error_dict = {'agnosis Discrep':1,
                   'imary Tumor Site Discrep':2,
                   'IPAA':0,
                   'rior Malignancy History':2,
                   'ual/Syn':1,
                   'ase is \(cir':1,
                   'eviewer Initials':2,
                   'ate Reviewed':1,
                   'ISQUALI':1}

    coord_dict = {'left':[],'top':[],'right':[],'bottom':[]}

    for block in blocks:
        if (block['BlockType'] == "LINE"):
            for keyword in list(keyword_dict.keys()):
                matches = regex.findall('('+keyword+'){e<='+str(error_dict[keyword])+'}',block['Text'])
                if len(matches) > 0:
                    match_list += matches
                    box=block['Geometry']['BoundingBox']
                    left = width * box['Left']
                    top = height * box['Top']
                    coord_dict['left'].append(left+width*keyword_dict[keyword]['left1'])
                    coord_dict['top'].append(top+height*keyword_dict[keyword]['top1'])
                    coord_dict['right'].append(left +width*keyword_dict[keyword]['left2'])
                    coord_dict['bottom'].append(top +height*keyword_dict[keyword]['top2'])

    #If QC table detected, take max of all bounding boxes for QC table
    if len(coord_dict['left'])>0:
        left_qc = min(coord_dict['left'])
        top_qc = min(coord_dict['top'])
        right_qc = max(coord_dict['right'])
        bottom_qc = max(coord_dict['bottom'])

        qc_box_area = (right_qc-left_qc)/width*(bottom_qc-top_qc)/height #area in units of proportion of pixels

        draw = ImageDraw.Draw(image)
        draw.rectangle([left_qc, top_qc, right_qc, bottom_qc], outline='black')

        #Save image with drawn rectangle
        if len(match_list) == 1:
            image.save(new_img_dir + img.replace('.jpg','')+'_tables_drawn.png')
        #display(image) #inline

        if qc_box_area >= .05:
            image.save(large_area_dir + img.replace('.jpg','')+'_tables_drawn.png')

    else:
        qc_box_area = 0
        left_qc, top_qc, right_qc, bottom_qc = 0,0,0,0
    return qc_box_area, {'left':left_qc, 'right':right_qc,'top':top_qc,'bottom':bottom_qc}, match_list



#Check if a contains b
def check_subset(a,b):
    #Note: (0,0) is the upper left hand corner of the coordinates
    if (a['left'] <= b['left'] and a['right'] >= b['right']):
         x_overlap = True
    else:
        x_overlap = False
    if (a['top'] <= b['top'] and a['bottom'] >= b['bottom']):
        y_overlap = True
    else:
        y_overlap = False
    if x_overlap and y_overlap:
        return True
    else:
        return False

#Check whether Two Rectangles Overlap
def rect_overlap(a,b):
    if ((a['right'] >= b['left']) and (a['right'] <= b['right'])) or ((a['left'] >= b['left']) and (a['left'] <= b['right'])):
         x_overlap = True
    else:
        x_overlap = False
    if ((a['top'] <= b['bottom']) and (a['top'] >= b['top'])) or ((a['bottom'] >= b['bottom']) and (a['bottom'] <= b['top'])):
        y_overlap = True
    else:
        y_overlap = False
    if x_overlap and y_overlap:
        return True
    else:
        return False

#Compute Area between Two Rectangles (Bounding Boxes) - as a proportion of the area of the line
def get_overlap_area(a,b): #(qc_box, line_box)
    mid_x = sorted([a['left'],a['right'],b['left'],b['right']])[1:3]
    width = abs(mid_x[0]-mid_x[1])
    mid_y = sorted([a['top'],a['bottom'],b['top'],b['bottom']])[1:3]
    height = abs(mid_y[0]-mid_y[1])
    return width*height/(abs(b['left']-b['right'])*abs(b['top']-b['bottom']))

#Check whether a line contains Printed or Handwritten Text (as detected by Textract)
def check_line_printed(line, words):

    type_list = []
    id_list = line['Relationships'][0]['Ids']

    for word_id in id_list:
        match = [a for a in words if a['Id'] == word_id][0] #unique id
        if len(match) > 0:
            type_list.append(match['TextType'])
    if set(type_list) != {'HANDWRITING'}:
        return True
    else:
        return False

#Remove TCGA QC Table and Handwritten Lines
def process_img(img, qc_box_coord):

    final_line_list = []

    image_file = 'imgs_for_aws/' + img #Image = Page from Pathology Report (Downloaded from TCGA Portal)
    response =  pickle.load( open('aws_response/'+img.replace('.jpg','')+'_response.p', "rb" ))
    blocks = response['Blocks']
    image=Image.open(image_file)
    draw = ImageDraw.Draw(image)
    width, height = image.size
    words = [a for a in blocks if a['BlockType']=='WORD']
    orig_n_lines = len([a for a in blocks if a['BlockType']=='LINE'])

    for block in blocks:

        if (block['BlockType'] == "LINE"):

            #remove the line if overlap >= 75% of its area with QC table bounding box

            line_coord = {}
            box=block['Geometry']['BoundingBox']
            left = width * box['Left']
            top = height * box['Top']
            line_coord['left']=left
            line_coord['top']= top
            line_coord['right']= left + (width * box['Width'])
            line_coord['bottom']=top +(height * box['Height'])

            #If line is subset of QC table, do not include in final list
            if check_subset(qc_box_coord,line_coord):
                pass
                #draw.rectangle([left,top, left + (width * box['Width']), top +(height * box['Height'])],outline='black')

            #If line overlaps with QC table > 25% of line's area, do not include in final list
            elif rect_overlap(qc_box_coord,line_coord) or rect_overlap(line_coord,qc_box_coord):
                overlap_area = get_overlap_area(qc_box_coord,line_coord)
                if overlap_area <=.25:

                    #If line contains only handwritten words, do not include in final list
                    if check_line_printed(block, words):
                        final_line_list.append(block['Text'])

                    #draw.rectangle([left,top, left + (width * box['Width']), top +(height * box['Height'])],outline='black')
            else:
                #If line contains only handwritten words, do not include in final list
                if check_line_printed(block, words):
                    final_line_list.append(block['Text'])

    if len(final_line_list)>0: #Automatically exclude empty pages
        pickle.dump(final_line_list, open(new_dir + img.replace('.jpg','')+'_lines.p', "wb") )
    return orig_n_lines - len(final_line_list)

def display_all(img, qc_box_coord):
    image_file = 'imgs_for_aws/' + img
    response =  pickle.load( open('textract_response/'+img.replace('.jpg','')+'_response.p', "rb" ))
    blocks = response['Blocks']
    image=Image.open(image_file)
    draw = ImageDraw.Draw(image)
    width, height = image.size
    draw.rectangle([qc_box_coord['left'], qc_box_coord['top'],
                    qc_box_coord['right'], qc_box_coord['bottom']], outline='black')
    for block in blocks:
        if (block['BlockType'] == "LINE"):
            line_coord = {}
            box=block['Geometry']['BoundingBox']
            left = width * box['Left']
            top = height * box['Top']
            line_coord['left']=left
            line_coord['top']=top
            line_coord['right']= left + (width * box['Width'])
            line_coord['bottom']=top +(height * box['Height'])
            draw.rectangle([left,top, left + (width * box['Width']), top +(height * box['Height'])],outline='black')

    display(image)

#Run QC Removal
lines_removed_dict = {}
med_conf_dict = {}
final_match_list = []
area_dict = {}
for i in range(len(response_list)):
    if i % 200 == 0:
        print(i, 'pages processed.')
    img = response_list[i].split('/')[1].replace('_response.p','.jpg')
    qc_area, qc_box_coord, interim_match_list = detect_qc_table(img)
    area_dict[img] = qc_area
    final_match_list += interim_match_list
    n_lines_removed = process_img(img, qc_box_coord)
    lines_removed_dict[img] = n_lines_removed

print('Number of pages with non-zero lines:', len(glob.glob(new_dir +'*.p')))
print('Total number of lines removed:',sum(list(lines_removed_dict.values())))

"""# Final Report Clean-up
# **Remove Non-clinically relevant (and potentially confounding) keywords from lines; Remove redaction artifacts and empty lines**
"""

import glob, os
import pickle
import pandas as pd
import shutil
import re
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns

#Create new directory for output

prev_dir = 'post_table_and_handwriting_removal/'
new_dir = 'post_keyword_and_empty_filtering/'
if not os.path.exists(new_dir):
	os.makedirs(new_dir)

#Data to be processed
current_files = glob.glob(prev_dir+'*.p')
print('Number of pages to process:',len(current_files))

#List of terms to match and remove
list_to_remove = ['\\*',
'^end[ ]*of[ ]*report$', #footer
'^\(end[ ]*of[ ]*report\)$', #footer
'page[ ]*(\S+)[ ]*of[ ]*(\S+)', #footer
'continued[ ]*on[ ]*next[ ]*page.*', #footer
'Translated[ ]*by.*', #footer
'^Edited by.*', #footer
'.*CONTACT[ ]*YOUR[ ]*DOCTOR[ ]*WITH[ ]*THIS[ ]*REPORT.*', #footer
'.*MM/DD/YYYY.*', #remove entire line containing this expression
'.*Ref[\. ]*Number.*', #header
'.*DOB.*', #header
'^D\.O\.B\..*', #header
'^B.?Day.*',#header
'.*Internal[ ]*Sample[ ]*ID.*', #header
'^Surg[ ]*Path[ ]*Final[ ]*Report.*$',
'^Surg\.[ ]*Path\.[ ]*No[ ]*.?:?#?$',
'^Surg[ ]*Path.?:?#?$',
'^Surgical[ ]*Pathology[ ]*.?:?#?$',
'^Surgical[ ]*Pathology[ ]*Report[ ]*.?:?#?$',
'^Surgical[ ]*Pathology[ ]*Final[ ]*.?:?#?[ ]*Report[ ]*.?:?#?$',
'^Surgical[ ]*Pathology[ ]*Consultation[ ]*Report[ ]*.?:?#?$',
'^Surgical[ ]*Pathology[ ]*.?:?#?[ ]*\[OrderID[ ]*.?:?#?$',
'^Surgical[ ]*Date[ ]*.?:?#?$',
'^Sample[ ]*.?:?#?.?:?#?$',
'^Sample[ ]*Number[ ]*.?:?#?$',
'^Sample[ ]*ID[ ]*.?:?#?$',
'^Sample Procurement:?[ ]*Date.*',
'^TCGA.*', #TCGA barcode remnants; accounting for variations encountered due to OCR mis-translation
'Redacted.*',
'^UUID.*',
'^JUID.*',
'^UID:.*',
'^JID:.*',
'^IID:.*',
'^ICGA.*',
'^ID[ ]*.?:?#?$',
'^D:\S+\-?\S+\-?\S+\-?\S+\-?\S+$',
'^D[ ]*:[ ]*\d+$',
'^ID[ ]*:[ ]*\S+\-?\S+\-?\S+\-?\S+\-?\S+$',
'^TCSA.*',
'^CGA.*',
'.*PATH\.[ ]*NO.?:?#?.*', #header
'^TSS.*', #header
'^[ ]*Tissue[ ]*Source[ ]*Site[ ]*.?:?#?', #header
'^Case[ ]*#.?.*',
'^Case.?:?#?[ ]*$',
'^Age \\(years\\).*',
'^Age.?:?$', #header
'.*Age/Sex.*', #header
'^Sex/Race.*$',#header
'^Tumor[ ]*ID.?:?#?$', #header
'^Date[ ]*.?:?#?$', #header
'^Date[ ]*Ordered[ ]*.?:?#?$',
'^Date[ ]*Signed[ ]*.?:?#?$',
'^Compliance[ ]*validated[ ]*by[ ]*.?:?#?$',
'^Collect[ ]*date.?:?#?',#header
'^Date[ ]*of[ ]*Procedure.?:?#?', #header
'.*Date[ ]*of[ ]*procurement[ ]*.?:?#?', #header
'.*Date[ ]*of[ ]*tumor procurement.*',#header
'^Date[ ]*of[ ]*report.*', #header
'^Date[ ]*of[ ]*Surgery.*', #header
'^Date[ ]*Reported.*',#header
'^Date[ ]*of.?[ ]*$',
'^Procurement[ ]*Date[ ]*.?:?#?',
'^Date[ ]*of[ ]*Receipt.*',#header
'.*Specimen[ ]*Date/Time[ ]*.?',#header
'^Unique[ ]*Patient[ ]*Identifier.*', #header
'MRN:.*',#header
'<Sign[ ]*Out[ ]*Dr\.[ ]*Signature>.*',
'^Accession[ ]*.?:?#?[ ]*$', #header
'^Acc#.*', #header
'^PHYSICIAN[ ]*&[ ]*PAGER[ ]*#.*',#header
'^Examination[ ]*No[ ]*\..?:?#?', #header
'^Patient[ ]*Name[ ]*.?:?#?[ ]*$', #header
'^Patient\'s[ ]*Name[ ]*.?:?#?[ ]*$', #header
'^Patient[ ]*Identification[ ]*.?:?#?$', #header
'^Patient[ ]*Results[ ]*:?#?[ ]*$', #header
'^Procurement[ ]*.?:?#?$$',#header
'Name[ ]*of[ ]*Pathologist.*',#header
'^Assistant[ ]*.?:?#?$', #header
'^Pathology[ ]*Assistant[ ]*.?:?#?$',
'^Pathologists\'[ ]*Assistant[ ]*.?:?#?$',
'^Performed[ ]*by[ ]*Pathologist\'s[ ]*Assistant[ ]*.?:?#?$',
'.*MED\.[ ]*REC\.[ ]*N.*', #header
'.*Med\.[ ]*Rec\.[ ]*#.*', #header
'^Admit[ ]*Protocol[ ]*.?:?#?$',
'\\(\\)', #empty parentheses
'\[[ ]*\]',
'Printed[ ]*by[ ]*.?:?#?$', #footer
'Printed[ ]*on[ ]*.?:?#?$', #footer
'^Verified[ ]*By.*',#footer
'Report[ ]*Electronically[ ]*Signed.*',#footer
'^History[ ]*Case[ ]*Pathology.*', #header
'^File[ ]*under.*', #header
'^Admitting Physician.*',
'^Result[ ]*Type.?:?#?$', #header
'^Result[ ]*Title.*', #header
'^Result[ ]*Status.?:?#?$', #header
'Patient:[ ]*XXX', #header
'^Examination performed on.*', #header
'^Internal[ ]*invoice.*', #header
'PESEL:[ ]*XXX.*',
'^OPER[ ]*.?:?#?$',
'^Service.?:?#?$',
'^Ref.?[ ]*Physician.*',
'^Account[ ]*#.?$',
'^OUTPATIENT.?:?#?$',
'^Patient[ ]*Address.*',
'^Billing.*$',
'.*Additional Copy to.*',
'^Ref\.[ ]*Source.*',
'^INPATIENT.?:?#?$',
'^Other[ ]*Related[ ]*Data.?:?#?$',
'^Financial[ ]*Number.*',
'^Performing[ ]*Clinician.?:?#?$',
'^Street[ ]*address.*',
'^Internal[ ]*postal[ ]*address.*',
'^Patient[ ]*Key.*$',
'^E\-mail.*$',
'^Concerning.?:?#?$',
'^Direct[ ]*dial[ ]*.?:?#?$',
'^Path.?\-[ ]*No.?.?[ ]*$',
'^Mobile[ ]*.?:?#?$',
'^Postal[ ]*address[ ]*.?:?#?$',
'^Pt\.[ ]*Phone[ ]*no[ ]*.?:?#?$',
'^PATIENT[ ]*PHONE[ ]*NO[ ]*.?:?#?$',
'^HCN[ ]*.?:?#?$',
'.*AP[ ]*Report[ ]*.?:?#?$',
'^Final[ ]*Report[ ]*.?:?#?$',
'^Document[ ]*Type[ ]*.?:?#?$',
'^Document[ ]*Status[ ]*.?:?#?$',
'^Document[ ]*.?:?#?$',
'^Auth[ ]*\\(Verified\\)',
'^Document[ ]*Title[ ]*.?:?#?$',
'^Anatomic[ ]*Pathology[ ]*Report[ ]*.?:?#?$',
'^Encounter[ ]*info[ ]*.?:?#?$',
'^Value[ ]*of[ ]*diagnostic[ ]*procedure[ ]*.?:?#?$',
'^Result[ ]*.?:?#?$',
'^Received?[ ]*.?.?:?#?$' ,
'^Entry[ ]*Information[ ]*.?:?#?$',
'^Seen[ ]*in[ ]*consultation[ ]*with[ ]*.?:?#?$',
'^continued[ ]*next[ ]*.?:?#?$',
'^Entry[ ]*Date[ ]*and[ ]*Time.?[ ]*$',
'^Lab[ ]*Status[ ]*.?:?#?$',
'^Entered[ ]*by[ ]*.?:?#?$',
'^Final[ ]*result[ ]*.?:?#?$',
'^Reported[ ]*by[ ]*.?:?#?$',
'^Report[ ]*.?:?#?$',
'^Physician[ ]*.?:?#?$',
'^Collected[ ]*.?:?#?$',
'^Specimen[ ]*Received*.?:?#?$',
'^Pathology[ ]*Number[ ]*.?:?#?$',
'^Inquiry[ ]*Number.?[ ]*.?:?#?$',
'^Received[ ]*Time[ ]*.?:?#?$',
'^Received[ ]*Date[ ]*.?:?#?$',
'^Time[ ]*Collected[ ]*.?:?#?$',
'^Time[ ]*Received[ ]*.?:?#?$',
'^Time[ ]*Reported[ ]*.?:?#?$',
'^Time[ ]*Transmitted[ ]*.?:?#?$',
'^Collected[ ]*Time[ ]*.?:?#?$',
'^CC:$',
'^Final[ ]*.?:?#?$',
'^Relevant Information[ ]*.?:?#?$',
'^Location[ ]*.?:?#?$',
'^Copied[ ]*To[ ]*.?:?#?$',
'^Report[ ]*Patient[ ]*.?:?#?$',
'^Name[ ]*.?:?#?$',
'^Accession[ ]*Number[ ]*.?:?#?$',
'^Reviewed[ ]*.?:?#?$',
'^Reviewed[ ]*and[ ]*electronically.*',
'^Reviewed[ ]*.?:?#?$',
'^Reviewed[ ]*by .*',
'^Reviewed[ ]*By[ ]*:?[ ]*List.*',
'^Grossed[ ]*by[ ]*:?.*',
'^Reviewed[ ]*by[ ]*dr.*',
'^Lab[ ]*Information[ ]*.?:?#?$',
'^Parent[ ]*Order[ ]*.?:?#?$',
'^Child[ ]*Order[ ]*.?:?#?$',
'^Result[ ]*Information[ ]*.?:?#?$',
'^Result[ ]*and Time[ ]*.?:?#?$',
'^Edited[ ]*.?:?#?$',
'^Entry[ ]*Date[ ]*.?:?#?$',
'^Component[ ]*Results[ ]*.?:?#?$',
'^Taken[ ]*.?:?#?$',
'^Physician\\(s\\)[ ]*.?:?#?$',
'^Reported[ ]*.?:?#?$',
'^Reported[ ]*Date[ ]*.?:?#?$',
'^BIRTH[ ]*.?:?#?$',
'^PAT[ ]*TYPE[ ]*.?:?#?$',
'^ADM[ ]*.?:?#?[ ]*.?:?#?$',
'^Unit[ ]*in[ ]*charge[ ]*.?:?#?$',
'^Physician[ ]*in[ ]*charge[ ]*.?:?#?$',
'^Material[ ]*collected[ ]*on[ ]*.?:?#?$',
'^Material[ ]*received[ ]*on[ ]*.?:?#?$',
'^Address[ ]*.?:?#?$',
'^MR[ ]*No[ ]*.?:?#?$',
'^Taken/Received[ ]*.?:?#?$',
'^Service[ ]*.?:?#?$',
'^Surgeon/physician[ ]*.?:?#?$',
'^Attending[ ]*Surgeon[ ]*.?:?#?$',
'^Surgeons?[ ]*.?.?:?#?$',
'^Gender[ ]*.?.?:?#?$',
'^Sex[ ]*.?.?:?#?$',
'^Case[ ]*Number[ ]*.?:?#?$',
'^Phone[ ]*.?.?:?#?$',
'^Fax[ ]*.?.?:?#?$',
'^\\(Continued\\)[ ]*.?:?#?$',
'^Tel[ ]*.?:?#?$',
'^Surname[ ]*.?:?#?$',
'^Surname[ ]*and[ ]*Name.?:?#?$',
'^Forename.?\\(s\\)[ ]*.?:?#?$',
'^Unit[ ]*.?:?#?$',
'^Request Date[ ]*.?:?#?$',
'^This[ ]*Copy[ ]*For[ ]*.?:?#?$',
'^Path#[ ]*.?:?#?$',
'^Staff[ ]*Pathologist[ ]*.?:?#?$',
'^Other[ ]*Pathologists[ ]*/[ ]*PAs[ ]*.?:?#?$',
'^Dictated[ ]*by[ ]*.?:?#?$',
'^MR[ ]*.?:?#?$',
'^Signature[ ]*.?:?#?$',
'^COMMITTEE.*',
'^Requested[ ]*by[ ]*.?:?#?$',
'^AP[ ]*Surgical[ ]*Pathology[ ]*.?:?#?$',
'^Performed[ ]*by[ ]*.?:?#?$',
'^Performed[ ]*by[ ]*the[ ]*staff[ ]*pathologist[ ]*.?:?#?$',
'^MED.?[ ]*REC[ ]*.?:?#?$',
'PATIENT[ ]*PHONE[ ]*.?:?#?$',
'^CONF[ ]*.?:?#?$',
'^Collection.*',
'^Print[ ]*time.*',
'^professor[ ]*of[ ]*pathology[ ]*.?:?#?$',
'Filed[ ]*automatically[ ]*on.*',
'^by[ ]*.?:?#?$',
'Report[ ]*electroni.*',
'^Electronic.*',
'Excision[ ]*date.*',
'Formatted[ ]*Path[ ]*Reports?[ ]*.?:?#?$',
'Compliance[ ]*vali[ ]*by.*',
'^Status[ ]*:[ ]*.?:?#?complete$',
'^Status[ ]*.?:?#?$',
'^Status[ ]*History[ ]*.?:?#?$',
'^Status[ ]*.?:?#?[ ]*Signed.*$',
'^Status[ ]*.?:?#?[ ]*Corrected$',
'^Status[ ]*:[ ]*.?:?#?supplemental$',
'^STATUS[ ]*:[ ]*SOUT[ ]*.?:?#?$',
'^Status[ ]*:[ ]*N/A[ ]*.?:?#?$',
'^Status[ ]*:[ ]*simed[ ]*Out[ ]*.?:?#?$',
'^Status[ ]*:[ ]*Ordered[ ]*.?:?#?$',
'^Status[ ]*Final[ ]*result[ ]*.?:?#?$',
'^Status:[ ]*Siman[ ]*Out[ ]*.?:?#?$',
'^Status[ ]*\\(Last[ ]*updated[ ]*Date/Time\\)[ ]*.?:?#?$',
'^Status:[ ]*Complete[ ]*as[ ]*of[ ]*.?:?#?$',
'^Status:[ ]*Final[ ]*resuit[ ]*.?:?#?$',
'^Status:[ ]*Final[ ]*result[ ]*.?:?#?$',
'^Status[ ]*of[ ]*Proceduze:[ ]*Signed[ ]*Out[ ]*.?:?#?$',
'^Status[ ]*:[ ]*DIS[ ]*IN[ ]*.?:?#?$',
'^Department[ ]*of[ ]*Cancer Pathology.*',
'^Department[ ]*of[ ]*Pathology[ ]*.?:?#?$',
'Submitting[ ]*Physician.*',
'^Resulting[ ]*Agency[ ]*.?:?#?$',
'^Provider[ ]*Information[ ]*.?:?#?$',
'Accessioned[ ]*on.*',
'CASE NO[ ]*.?:?#?$',
'^OpenClinica.*',
'^Order.*',
'^Test[ ]*performed[ ]*at.*',
'Addendum[ ]*Report[ ]*Issued.*',
'^MRN[ ]*.?:?#?[ ]*.?:?#?[ ]*.?:?#$',
'This[ ]*report[ ]*has[ ]*been[ ]*finalized.*',
'^FMP/SSN.*',
'^SSN.*',
'^Referring[ ]*Physician[ ]*.?:?#?$',
'^Subm[ ]*Dr[ ]*.?:?#?.?:?#?$',
'^Acct[ ]*.?:?#?$',
'^Reg[ ]*.?:?#?$',
'^Disch[ ]*.?:?#?$',
'^Att[ ]*Dr.*',
'^Req[ ]*.?:?#?$',
'^Ref[ ]*.?:?#?$',
'^Hosp[ ]*.?:?#?$',
'^Prov[ ]*.?:?#?$',
'^\\(FINAL\\)[ ]*.?:?#?$',
'^Patient[ ]*Na[ ]*.?:?#?$',
'Visit[ ]*.?:?#?$',
'^Path[ ]*.?:?#?$',
'^Primary[ ]*Path[ ]*.?:?#?$',
'^Resident[ ]*Path[ ]*.?:?#?$',
'^Copath[ ]*[ ]*.?:?#?$',
'^Department[ ]*:[ ]*PATH[ ]*.?:?#?$',
'^Formatted[ ]*Path[ ]*.?:?#?$',
'Copy[ ]*To.*',
'^Transcribed[ ]*by.*',
'^Surgery[ ]*.?:?#?$',
'^XX[ ]*.?:?#?$',
'^XXX+[ ]*.?:?#?$',
'^Signed[ ]*.?:?#?$',
'^Signed[ ]*out[ ]*.?:?#?$',
'^Signed[ ]*by[ ]*.?:?#?$',
'^Signed[ ]*out[ ]*by[ ]*.?:?#?$',
'^\[][ ]*.?:?#?$',
'Surg[ ]*Date.*',
'^TBCF#[ ]*.?:?#?$:',
'^Gross[ ]*Dictation.*',
'^Unique[ ]*Patient[ ]*.?:?#?$',
'^Hospital[ ]*.?:?#?$',
'^Patient[ ]*Type[ ]*.?:?#?$',
'^Physician[ ]*Copy[ ]*.?:?#?$',
'^PATHOLOGY[ ]*REPORT[ ]*.?:?#?$',
'^Component[ ]*Results[ ]*.?:?#?$',
'Patient[ ]*Number[ ]*.?:?#?$',
'Room/Bed.*',
'Ethnicity \\(Race\\)[ ]*.?:?#?$',
'^Cancer[ ]*Sample[ ]*.?:?#?$',
'^Page[ ]*.?:?#?$',
'^Page:[ ]*(S+)$',
'^Pathologist[ ]*.?:?#?$',
'^Patient[ ]*.?:?#?$',
'^PAT[ ]*TYPE[ ]*.?:?#?$',
'.*1974.*',#PRIVACY ACT OF 1974
'^No[ ]*.?:?#?$',
'^Yes[ ]*.?:?#?$',
'^\.+$',
'^,+$',
'^:+$',
'^-+$',
'^Collect[ ]*.?:?#?$',
'^[:\.,\)\(\?\*;]?[ ]*[:\.,\)\(\?\*;-]?[ ]*[:\.,\)\(\*;]?[ ]*[:\.,\)\(\?\*;-]?[ ]*[:\.,\)\(\*;-]?$'] #Matches if a line contains only punctuation (with any number of spaces in between)


#List of terms that require capitalization for specific-matching
full_cap_list=['.*DOB.*','^D\.O\.B\..*',
'^DOB.*',
'^UUID.*',
'^JUID.*',
'^UID:.*',
'^JID:.*',
'^ICGA.*',
'^ID[ ]*.?:?#?$',
'^TCSA.*',
'^CGA.*',
'^TCGA.*',
'^HCN[ ]*.?:?#?$',
'^TSS.*']


#List of terms that require specifically the first letter to be capitalized for matching
capitalize_first_letter = ['^Case[ ]*#.?.*',
'^Case.?:?#?[ ]*$',
'^Patient[ ]*.?:?#?$',
'^Patient[ ]*Name[ ]*.?:?#?[ ]*$', #header
'^Patient\'s[ ]*Name[ ]*.?:?#?[ ]*$',
'^Patient[ ]*Identification[ ]*.?:?#?$', #header
'^Patient[ ]*Results[ ]*:?#?[ ]*$', #header
'PATIENT[ ]*PHONE[ ]*.?:?#?$',
'^PATIENT[ ]*PHONE[ ]*NO[ ]*.?:?#?$',
'Patient:[ ]*XXX', #header
'^Patient[ ]*Na[ ]*.?:?#?$',
'^Patient[ ]*Address.*',
'^Patient[ ]*Key.*$',
'^Patient[ ]*Type[ ]*.?:?#?$',
'Patient[ ]*Number[ ]*.?:?#?$',
'^Sample[ ]*.?:?#?.?:?#?$',
'^Sample[ ]*Number[ ]*.?:?#?$',
'^Sample[ ]*ID[ ]*.?:?#?$',
'^Sample Procurement:?[ ]*Date.*',
'^Taken[ ]*.?:?#?$',
'^Reported[ ]*.?:?#?$',
'^Reported[ ]*by[ ]*.?:?#?$',
'^Reported[ ]*Date[ ]*.?:?#?$',
'^Order.*',
'^Collection.*',
'^Procurement[ ]*.?:?#?$',
'^Procurement[ ]*Date[ ]*.?:?#?$',
'^Status[ ]*:[ ]*.?:?#?complete$',
'^Status[ ]*.?:?#?$',
'^Status[ ]*History[ ]*.?:?#?$',
'^Status[ ]*.?:?#?[ ]*Signed.*$',
'^Status[ ]*.?:?#?[ ]*Corrected$',
'^Status[ ]*:[ ]*.?:?#?supplemental$',
'^STATUS[ ]*:[ ]*SOUT[ ]*.?:?#?$',
'^Status[ ]*:[ ]*N/A[ ]*.?:?#?$',
'^Status[ ]*:[ ]*simed[ ]*Out[ ]*.?:?#?$',
'^Status[ ]*:[ ]*Ordered[ ]*.?:?#?$',
'^Status[ ]*Final[ ]*result[ ]*.?:?#?$',
'^Status:[ ]*Siman[ ]*Out[ ]*.?:?#?$',
'^Status[ ]*\\(Last[ ]*updated[ ]*Date/Time\\)[ ]*.?:?#?$',
'^Status:[ ]*Complete[ ]*as[ ]*of[ ]*.?:?#?$',
'^Status:[ ]*Final[ ]*resuit[ ]*.?:?#?$',
'^Status:[ ]*Final[ ]*result[ ]*.?:?#?$',
'^Status[ ]*of[ ]*Proceduze:[ ]*Signed[ ]*Out[ ]*.?:?#?$',
'^Status[ ]*:[ ]*DIS[ ]*IN[ ]*.?:?#?$',
'^Reviewed[ ]*.?:?#?$',
'^Reviewed[ ]*and[ ]*electronically.*',
'^Reviewed[ ]*.?:?#?$',
'^Reviewed[ ]*by .*',
'^Reviewed[ ]*By[ ]*:?[ ]*List.*',
'^Surgeon/physician[ ]*.?:?#?$',
'^Surgeons?[ ]*.?.?:?#?$',
'^Pathologist[ ]*.?:?#?$',
'^Surgical[ ]*Pathology[ ]*.?:?#?$',
'^Surgical[ ]*Pathology[ ]*Report[ ]*.?:?#?$',
'^Surgical[ ]*Pathology[ ]*Final[ ]*.?:?#?[ ]*Report[ ]*.?:?#?$',
'^Surgical[ ]*Pathology[ ]*Consultation[ ]*Report[ ]*.?:?#?$',
'^Surgical[ ]*Pathology[ ]*.?:?#?[ ]*\[OrderID[ ]*.?:?#?$',
'^Surgical[ ]*Date[ ]*.?:?#?$']

#Define function for line removal, specifying capitalization conditions for keywords as outlined above
def process_line(new_line, list_to_remove, keyword_lines_removed_dict):

    for element in list_to_remove:

        old_line = new_line
        prev = len(old_line)

        if element in full_cap_list:
            if element == '.*DOB.*':
                if 'ENDOBRONCHIAL' not in new_line:
                    new_line = re.sub(element, "", new_line).strip()
            else:
                new_line = re.sub(element, "", new_line).strip()

        elif element in capitalize_first_letter:
            if len(new_line) > 0:
                if new_line[0].isupper():
                    new_line = re.sub(element, "", new_line, flags=re.IGNORECASE).strip()

        else:
            if element in ['^No[ ]*.?:?#?$','^Yes[ ]*.?:?#?$']:
                if (i != 0) and lines[i-1].strip()[-1]==':': #Ammending yes/no removal
                    pass
                else:
                    new_line = re.sub(element, "", new_line, flags=re.IGNORECASE).strip()
            new_line = re.sub(element, "", new_line, flags=re.IGNORECASE).strip()

        if len(new_line) != prev:
            keyword_lines_removed_dict[element].append(old_line)

    return new_line, keyword_lines_removed_dict

#Track lines removed (and which keywords trigger removal)
keyword_lines_removed_dict = {elem:[] for elem in list_to_remove}
n_lines_removed_dict = {}

#Track number of empty pages (removed)
n_empty_pages = 0

#Note: The below code may take some time to run
for j in range(len(current_files)):

    p = current_files[j]
    n_lines_removed = 0
    new_lines = []
    lines = pickle.load(open(p, "rb"))

    for i in range(len(lines)):

        len_line = len(lines[i])
        new_line = lines[i].strip() #Remove leading and trailing whitespace
        new_line = re.sub(' {2,}', ' ', new_line) #Remove >1 white space between words

        #3x keyword removal
        for cycle in range(3):
            new_line, keyword_lines_removed_dict = process_line(new_line, list_to_remove, keyword_lines_removed_dict)


        if (len_line != 0) and (len(new_line)==0):
            n_lines_removed +=1
        #Remove lines that were originally empty or whitespace, or that are now whitespace
        elif (len_line != 0) and (len(lines[i].strip())!=0) and (len(new_line.strip())!= 0):
            new_lines.append(new_line)

    #Only save non-empty pages
    if len(new_lines) > 0:
        pickle.dump(new_lines, open(new_dir + p.replace(prev_dir,""),"wb"))
    else:
        n_empty_pages +=1
    n_lines_removed_dict[p.replace(prev_dir,'').replace('_lines.p','')] = n_lines_removed

    #Track progress
    if j % 2000 == 0:
        print(j,' pages finished.')

print(n_empty_pages,' empty pages, removed.')

"""IMPORTANT NOTE : To prepare the text for input, we joined all lines and pages across each patient report. Resulting in a CSV file with 2 columns: patient_filename and text

We also have a CSV file of the metadata (cancer_types) with also 2 columns: patient_id and cancer_type

We next merged the reports CSV with the labels CSV into one CSV file for further processig and training + evaluating the model that we aim to use
"""